"""empty message

Revision ID: 2d0bd0482096
Revises: a58db85af291
Create Date: 2024-08-21 21:52:47.465416

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d0bd0482096"
down_revision = "a58db85af291"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_carts_user", "users", ["user_id"], ["id"])

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.BOOLEAN(),
            type_=sa.String(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.String(),
            type_=sa.BOOLEAN(),
            existing_nullable=False,
        )

    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_carts_user", type_="foreignkey")

    # ### end Alembic commands ###
