"""empty message

Revision ID: a754a3ab7ee4
Revises: ad5cd4520d77
Create Date: 2024-08-28 08:47:07.671822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a754a3ab7ee4'
down_revision = 'ad5cd4520d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
